
# Verify source file choice:
# ('java' would fail)
typing_a::choices('python','c++'),load('typing'): python 

# Verify final resolved value choice:
# ('python' would fail, as it is soft-typed
typing_b::load('typing'),choices('hard'): java 

# Verify source file and final resolved value choices
# ('java' and 'python' would fail)
typing_c::choices('c++', 'python'),load('typing'),choices('hard'): c++ 
