
base: red
secondary: "$: 'green' if f_('base')=='red' else 'red'" # Ref from file root.

# $-strings; hidden,choices
# fancy_versions::hidden: "$: {'red':'fuscia', 'green':'chartreuse'}" # Also valid
fancy_versions::hidden: 
  red: fuscia
  green: chartreuse
fancy_base:str:choices(*list(values(r_('fancy_versions')))): "$: f_('fancy_versions')[f_('base')]"
# "fancy_base:str:choices('fuscia', 'chartreuse')": "$: r_('fancy_versions')[r_('base')]"
fancy_secondary:str: "$: r_('fancy_versions')[r_('secondary')]"

# Load
layout::load('layouts'): splashes
alternate_layout::load: layouts/rainbow

# Choices
stroke_width::choices(5,10,15): 5
"temperature::choices('hot','cold')": cold

# Numpy datetime64 timestamps
target_time: "$: dt64('2023-10-10T10:05')"

